import Image from "next/image";
import React from "react";
import { Headland_One } from "next/font/google";

const headland = Headland_One({ weight: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "my-next-app|About",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className={`${headland.className}hero bg-base-200 min-h-screen`}>
      <div className="hero-content flex-col lg:flex-row-reverse">
        <Image
          src="https://img.daisyui.com/images/stock/photo-1635805737707-575885ab0820.webp"
          className="max-w-sm rounded-lg shadow-2xl"
          alt=""
          width={500}
          height={500}
        />
        <div>
          <h1 className="text-5xl font-bold">About Page!</h1>
          <h1 className="text-xl font-bold">Box Office News!</h1>
          <p className="py-6">
            Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda
            excepturi exercitationem quasi. In deleniti eaque aut repudiandae et
            a id nisi.
          </p>
          <button className="btn btn-primary">Get Started</button>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
